# Form implementation generated from reading ui file '.\asymmetric\rsa\rsa_ui.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(685, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(685, 520))
        MainWindow.setMaximumSize(QtCore.QSize(685, 650))
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0,0);")
        self.centralwidget.setObjectName("centralwidget")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(460, 50, 151, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: white;\n"
"font: 14pt \"Century Gothic\";\n"
"font-weight: 700;")
        self.label_9.setObjectName("label_9")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 701, 41))
        self.frame.setStyleSheet("background-color: rgb(49, 80, 78)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 691, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setStyleSheet("color: white;\n"
"font: 18pt \"Century Gothic\";\n"
"font-weight: 700;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(130, 50, 61, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: white;\n"
"font: 14pt \"Century Gothic\";\n"
"font-weight: 700;")
        self.label_8.setObjectName("label_8")
        self.textBrowser_encrypted = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_encrypted.setGeometry(QtCore.QRect(380, 80, 290, 120))
        self.textBrowser_encrypted.setStyleSheet("background-color: rgb(42, 42, 42);\n"
"border: 1px solid gray;\n"
"border-radius: 10px;\n"
"color: white;\n"
"")
        self.textBrowser_encrypted.setObjectName("textBrowser_encrypted")
        self.text_edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_edit.setGeometry(QtCore.QRect(20, 80, 290, 120))
        self.text_edit.setStyleSheet("background-color: rgb(42, 42, 42);\n"
"border: 1px solid gray;\n"
"border-radius: 10px;\n"
"color: white;\n"
"")
        self.text_edit.setObjectName("text_edit")
        self.input_path = QtWidgets.QLabel(self.centralwidget)
        self.input_path.setGeometry(QtCore.QRect(180, 470, 141, 30))
        self.input_path.setStyleSheet("color: white;\n"
"font: 14pt \"Century Gothic\";\n"
"font-weight: 700;\n"
"text-transform: uppercase;\n"
"")
        self.input_path.setObjectName("input_path")
        self.input_file_btn = QtWidgets.QPushButton(self.centralwidget)
        self.input_file_btn.setGeometry(QtCore.QRect(20, 470, 151, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.input_file_btn.setFont(font)
        self.input_file_btn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: grey;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(102, 102, 102);\n"
"}")
        self.input_file_btn.setObjectName("input_file_btn")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 210, 651, 214))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_key_size = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_key_size.setFont(font)
        self.label_key_size.setStyleSheet("color: white;")
        self.label_key_size.setObjectName("label_key_size")
        self.verticalLayout_2.addWidget(self.label_key_size)
        self.label_p = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_p.setFont(font)
        self.label_p.setStyleSheet("color: white;")
        self.label_p.setObjectName("label_p")
        self.verticalLayout_2.addWidget(self.label_p)
        self.label_q = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_q.setFont(font)
        self.label_q.setStyleSheet("color: white;")
        self.label_q.setObjectName("label_q")
        self.verticalLayout_2.addWidget(self.label_q)
        self.label_public_key = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_public_key.setFont(font)
        self.label_public_key.setStyleSheet("color: white;")
        self.label_public_key.setObjectName("label_public_key")
        self.verticalLayout_2.addWidget(self.label_public_key)
        self.label_private_key = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_private_key.setFont(font)
        self.label_private_key.setStyleSheet("color: white;")
        self.label_private_key.setObjectName("label_private_key")
        self.verticalLayout_2.addWidget(self.label_private_key)
        self.label_n = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_n.setFont(font)
        self.label_n.setStyleSheet("color: white;")
        self.label_n.setObjectName("label_n")
        self.verticalLayout_2.addWidget(self.label_n)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.spinBox_key_len = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.spinBox_key_len.setFont(font)
        self.spinBox_key_len.setStyleSheet("color: white;")
        self.spinBox_key_len.setMinimum(9)
        self.spinBox_key_len.setMaximum(9999)
        self.spinBox_key_len.setObjectName("spinBox_key_len")
        self.verticalLayout_3.addWidget(self.spinBox_key_len)
        self.lineEdit_p = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_p.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_p.setFont(font)
        self.lineEdit_p.setStyleSheet("border: 1px solid #ccc;\n"
"color: white;")
        self.lineEdit_p.setReadOnly(False)
        self.lineEdit_p.setObjectName("lineEdit_p")
        self.verticalLayout_3.addWidget(self.lineEdit_p)
        self.lineEdit_q = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_q.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_q.setFont(font)
        self.lineEdit_q.setStyleSheet("border: 1px solid #ccc;\n"
"color: white;")
        self.lineEdit_q.setReadOnly(False)
        self.lineEdit_q.setObjectName("lineEdit_q")
        self.verticalLayout_3.addWidget(self.lineEdit_q)
        self.lineEdit_public_key = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_public_key.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_public_key.setFont(font)
        self.lineEdit_public_key.setStyleSheet("border: 1px solid #ccc;\n"
"color: white;")
        self.lineEdit_public_key.setReadOnly(True)
        self.lineEdit_public_key.setObjectName("lineEdit_public_key")
        self.verticalLayout_3.addWidget(self.lineEdit_public_key)
        self.lineEdit_private_key = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_private_key.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_private_key.setFont(font)
        self.lineEdit_private_key.setStyleSheet("border: 1px solid #ccc;\n"
"color: white;")
        self.lineEdit_private_key.setReadOnly(True)
        self.lineEdit_private_key.setObjectName("lineEdit_private_key")
        self.verticalLayout_3.addWidget(self.lineEdit_private_key)
        self.lineEdit_n = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_n.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_n.setFont(font)
        self.lineEdit_n.setStyleSheet("border: 1px solid #ccc;\n"
"color: white;")
        self.lineEdit_n.setReadOnly(True)
        self.lineEdit_n.setObjectName("lineEdit_n")
        self.verticalLayout_3.addWidget(self.lineEdit_n)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.encrypt_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.encrypt_btn.setFont(font)
        self.encrypt_btn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: grey;\n"
"    border-radius: 7px;\n"
"    height: 30px;\n"
"    padding: 0px 7px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(102, 102, 102);\n"
"}")
        self.encrypt_btn.setObjectName("encrypt_btn")
        self.verticalLayout.addWidget(self.encrypt_btn)
        self.decrypt_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.decrypt_btn.setFont(font)
        self.decrypt_btn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: grey;\n"
"    border-radius: 7px;\n"
"    height: 30px;\n"
"    padding: 0px 7px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(102, 102, 102);\n"
"}")
        self.decrypt_btn.setObjectName("decrypt_btn")
        self.verticalLayout.addWidget(self.decrypt_btn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gen_p_q_btn = QtWidgets.QPushButton(self.centralwidget)
        self.gen_p_q_btn.setGeometry(QtCore.QRect(20, 430, 151, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.gen_p_q_btn.setFont(font)
        self.gen_p_q_btn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: grey;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(102, 102, 102);\n"
"}")
        self.gen_p_q_btn.setObjectName("gen_p_q_btn")
        self.gen_keys_btn = QtWidgets.QPushButton(self.centralwidget)
        self.gen_keys_btn.setGeometry(QtCore.QRect(180, 430, 151, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.gen_keys_btn.setFont(font)
        self.gen_keys_btn.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: grey;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(102, 102, 102);\n"
"}")
        self.gen_keys_btn.setObjectName("gen_keys_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA"))
        self.label_9.setText(_translate("MainWindow", "ШИФРОТЕКСТ"))
        self.label_4.setText(_translate("MainWindow", "RSA"))
        self.label_8.setText(_translate("MainWindow", "ТЕКСТ"))
        self.input_path.setText(_translate("MainWindow", "NO INPUT FILE"))
        self.input_file_btn.setText(_translate("MainWindow", "Входной файл"))
        self.label_key_size.setText(_translate("MainWindow", "Размер ключа"))
        self.label_p.setText(_translate("MainWindow", "P"))
        self.label_q.setText(_translate("MainWindow", "Q"))
        self.label_public_key.setText(_translate("MainWindow", "Открытый ключ"))
        self.label_private_key.setText(_translate("MainWindow", "Секретный ключ"))
        self.label_n.setText(_translate("MainWindow", "N"))
        self.encrypt_btn.setText(_translate("MainWindow", "Зашифровать"))
        self.decrypt_btn.setText(_translate("MainWindow", "Расшифровать"))
        self.gen_p_q_btn.setText(_translate("MainWindow", "Сгенерировать P и Q"))
        self.gen_keys_btn.setText(_translate("MainWindow", "Вычислить ключи"))
